language: ruby

git:
  submodules: false

before_install:
  - echo "Installing test gems"
  - gem install yaml-lint

install: true

# Validating the template and checking the linting
script:
  - yaml-lint template.yml

after_success:
  - echo "Test Success - Branch($TRAVIS_BRANCH) Pull Request($TRAVIS_PULL_REQUEST) Tag($TRAVIS_TAG)"
  - echo "Cloudformation template validated, YAML linted!"

# provisioning after test past after the test past successfully
deploy:
  provider: cloudformation
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_ACCESS_KEY
  region: "us-east-1"
  template: template.yml
  stack_name: tikal-eb
  capabilities: "CAPABILITY_NAMED_IAM"
  edge: true # opt in to dpl v2
  on:
    branch: main